# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20160418_1507'),
        ('userprofiles', '0006_shippingaddress_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount', models.IntegerField()),
                ('charge_id', models.CharField(blank=True, max_length=60, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='lists.ListItem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='userprofiles.UserProfile')),
            ],
        ),
    ]
