# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_pledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='charge_id',
            field=models.CharField(max_length=60),
        ),
    ]
