# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160413_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
