# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_list_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
