# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_pledge_stripe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
