# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20160415_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='stripe_token',
            new_name='charge_id',
        ),
    ]
