# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20160416_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='charge_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
