# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20160418_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Pledge',
        ),
    ]
