# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20160418_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
